options:
  git_repo:
    type: string
    default: ""
    description: |
      URL of the git repository to be cloned. It should contain a playbook.
      The URL can be any of the URLs supported by the git client.
      Thus, URLs such as http://username:password@mydomain.org/myplaybook.git
      can also be provided.
  playbook_yaml:
    type: string
    default: "playbook.yaml"
    description: The filename of the main YAML in the playbook to be executed.
  git_deploy_key:
    type: string
    default: ""
    description: |
      Optional SSH private key that can be used to clone the git repository
      over SSH.
  git_branch:
    type: string
    default: "master"
    description: git branch to check out after cloning the git repository.
  update_eval:
    type: string
    default: "/bin/true"
    description: |
      Optional bash expression to be evaluated at the update hook (every 5
      minutes).

      The expression should check for a condition to hold (e.g. the presence of
      a specific parameter in a configuration file).

      Thus, if the expression returns 0 (true), the playbook is NOT executed.
      Else, the playbook is executed.

      Please note that the playbook is executed unconditionally in all the other
      cases, i.e. when the configuration changes, a relation is joined, etc.
  hostgroup:
    type: string
    default: ""
    description: Optional host group to which localhost is added.
  become:
    type: boolean
    default: true
    description: Set the -b flag in the ansible-playbook command.
  tags:
    type: string
    default: ""
    description: |
      Only run plays and tasks tagged with these values 
      (-t option of the ansible-playbook command).
  inventory_dir:
    type: string
    default: ""
    description: |
      Inventory directory, relative to the git repository root.
      In this way, inventory directories such as group_vars and host_vars can be 
      made available to Ansible.
